server:
  port: 8080

spring:
  application:
    name: api-gateway

  loki:
    url: http://localhost:3100/loki/api/v1/push

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

        - id: vacancy-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/vacancies/**

        - id: resume-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/resumes/**

        - id: application-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/applications/**

jwt:
  secret: "supersecretkeyforjwtinjobexchange"

  logging:
    level:
      org.springframework.cloud.gateway: INFO
      com.vlz: DEBUG
