server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    default: local
  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: ${secret-jwt-key}

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

        - id: role-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/roles/**

        - id: vacancy-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/vacancies/**

        - id: company-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/companies/**

        - id: resume-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/resumes/**

        - id: education-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/educations/**

        - id: skill-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/skills/**

        - id: application-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/applications/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.vlz: DEBUG

app:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"